### ISSUE TITLE
Ignore 5xx status codes

### ISSUE THREAD

**Issue by hekike** [DaMouse404/koa-cache-control#15]
Shouldn't we skip 5xx status codes from caching?

**Comment by Mousius** [comment]
Hi @hekike,

One of the reasons for allowing 5xx codes to be cached is that if your system is in a bad state it makes sense to send a short `max-age` to reduce load. This can be seen as the second example in https://github.com/DaMouse404/koa-cache-control#overriding-defaults

**Comment by hekike** [comment]
Ok, I think it can be both good and bad, so I close this issue :)
