### ISSUE TITLE
Support Koa v2 middleware syntax

### ISSUE THREAD

**Issue by nfantone** [DaMouse404/koa-cache-control#3]
Update module to accommodate to new Promise-based middlewares, according to the [upgrading tips](https://github.com/koajs/koa/issues/533) on the Koa repo.

**Comment by Mousius** [comment]
Apologies this has been sat around for so long. I've just published `2.0.0-alpha.1` to NPM using the promise-based approach. 

This currently sits in https://github.com/DaMouse404/koa-cache-control/tree/koa-v2.

**Comment by Mousius** [comment]
Now `2.0.0-alpha.2` on NPM so I could tag it as `next` rather than `latest` and not impact existing users.

See here for more: https://medium.com/@mbostock/prereleases-and-npm-e778fc5e2420

**Comment by Mousius** [comment]
I've now published [2.0.0](https://github.com/DaMouse404/koa-cache-control/releases/tag/v2.0.0) to match with Koa's publishing of [2.0.1](https://github.com/koajs/koa/releases/tag/2.0.1).

**Comment by Mousius** [comment]
This has been working for awhile now so closing 😸
